#!/usr/bin/env python3
"""
Analytics Logger - Comprehensive logging for trading analysis and statistics

Logs everything in structured JSON format for easy analysis:
- Trades: Every execution with full details
- Decisions: Why trades were made or skipped
- Signals: All signals generated by strategies
- Performance: P&L snapshots, win rates, metrics
- Market Data: Price snapshots, indicators
- System: Errors, mode changes, connections
"""

import json
import csv
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict
from enum import Enum
import threading
import gzip
import shutil


class LogCategory(Enum):
    TRADE = "trades"
    DECISION = "decisions"
    SIGNAL = "signals"
    PERFORMANCE = "performance"
    MARKET_DATA = "market_data"
    SYSTEM = "system"
    ERROR = "errors"


@dataclass
class TradeLog:
    """Log entry for executed trades"""
    timestamp: str
    symbol: str
    action: str  # BUY, SELL, SHORT, COVER
    quantity: int
    price: float
    order_type: str  # MARKET, LIMIT, STOP
    side: str  # long, short
    reason: str
    strategy: str
    confidence: float
    stop_loss: float
    take_profit: float
    position_value: float
    account_balance: float
    mode: str  # simulation, live
    order_id: Optional[str] = None
    fill_price: Optional[float] = None
    commission: float = 0.0
    slippage: float = 0.0


@dataclass
class DecisionLog:
    """Log entry for trading decisions"""
    timestamp: str
    symbol: str
    decision: str  # ENTER, EXIT, HOLD, SKIP
    reason: str
    factors: Dict[str, Any]
    signals: Dict[str, float]
    indicators: Dict[str, float]
    risk_assessment: Dict[str, Any]
    confidence: float
    mode: str


@dataclass
class SignalLog:
    """Log entry for strategy signals"""
    timestamp: str
    symbol: str
    strategy: str
    signal: str  # BUY, SELL, NEUTRAL
    strength: float
    indicators: Dict[str, float]
    conditions_met: List[str]
    price: float
    volume: float


@dataclass
class PerformanceLog:
    """Log entry for performance snapshots"""
    timestamp: str
    account_balance: float
    daily_pnl: float
    total_pnl: float
    unrealized_pnl: float
    realized_pnl: float
    win_rate: float
    profit_factor: float
    sharpe_ratio: float
    max_drawdown: float
    current_drawdown: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    avg_win: float
    avg_loss: float
    largest_win: float
    largest_loss: float
    open_positions: int
    buying_power: float
    mode: str


@dataclass
class MarketDataLog:
    """Log entry for market data snapshots"""
    timestamp: str
    symbol: str
    price: float
    bid: float
    ask: float
    volume: float
    day_high: float
    day_low: float
    day_open: float
    prev_close: float
    change_pct: float
    indicators: Dict[str, float]


@dataclass
class SystemLog:
    """Log entry for system events"""
    timestamp: str
    event: str
    level: str  # INFO, WARNING, ERROR, CRITICAL
    message: str
    details: Dict[str, Any]


class AnalyticsLogger:
    """Centralized analytics logging system"""

    def __init__(self, log_dir: str = "logs/analytics"):
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # Create subdirectories for each category
        for category in LogCategory:
            (self.log_dir / category.value).mkdir(exist_ok=True)

        # File handles for current day's logs
        self._file_handles: Dict[LogCategory, Any] = {}
        self._current_date = datetime.now().date()
        self._lock = threading.Lock()

        # In-memory buffers for quick stats
        self._trade_buffer: List[TradeLog] = []
        self._performance_buffer: List[PerformanceLog] = []

        # Initialize log files
        self._init_log_files()

    def _init_log_files(self):
        """Initialize log files for current date"""
        date_str = self._current_date.strftime("%Y-%m-%d")

        for category in LogCategory:
            filepath = self.log_dir / category.value / f"{date_str}.jsonl"
            self._file_handles[category] = filepath

    def _check_date_rollover(self):
        """Check if we need to roll over to a new day's log files"""
        current_date = datetime.now().date()
        if current_date != self._current_date:
            self._current_date = current_date
            self._init_log_files()
            # Archive old logs
            self._archive_old_logs()

    def _archive_old_logs(self, days_to_keep: int = 30):
        """Archive logs older than specified days"""
        cutoff_date = datetime.now().date() - timedelta(days=days_to_keep)

        for category in LogCategory:
            category_dir = self.log_dir / category.value
            archive_dir = category_dir / "archive"
            archive_dir.mkdir(exist_ok=True)

            for log_file in category_dir.glob("*.jsonl"):
                try:
                    file_date = datetime.strptime(log_file.stem, "%Y-%m-%d").date()
                    if file_date < cutoff_date:
                        # Compress and move to archive
                        with open(log_file, 'rb') as f_in:
                            with gzip.open(archive_dir / f"{log_file.name}.gz", 'wb') as f_out:
                                shutil.copyfileobj(f_in, f_out)
                        log_file.unlink()
                except ValueError:
                    pass  # Skip files that don't match date pattern

    def _write_log(self, category: LogCategory, data: Dict[str, Any]):
        """Write a log entry to the appropriate file"""
        with self._lock:
            self._check_date_rollover()
            filepath = self._file_handles[category]

            with open(filepath, 'a') as f:
                f.write(json.dumps(data, default=str) + '\n')

    def log_trade(self, trade: TradeLog):
        """Log a trade execution"""
        self._write_log(LogCategory.TRADE, asdict(trade))
        self._trade_buffer.append(trade)

        # Keep buffer size manageable
        if len(self._trade_buffer) > 1000:
            self._trade_buffer = self._trade_buffer[-500:]

    def log_decision(self, decision: DecisionLog):
        """Log a trading decision"""
        self._write_log(LogCategory.DECISION, asdict(decision))

    def log_signal(self, signal: SignalLog):
        """Log a strategy signal"""
        self._write_log(LogCategory.SIGNAL, asdict(signal))

    def log_performance(self, perf: PerformanceLog):
        """Log performance snapshot"""
        self._write_log(LogCategory.PERFORMANCE, asdict(perf))
        self._performance_buffer.append(perf)

        if len(self._performance_buffer) > 1000:
            self._performance_buffer = self._performance_buffer[-500:]

    def log_market_data(self, data: MarketDataLog):
        """Log market data snapshot"""
        self._write_log(LogCategory.MARKET_DATA, asdict(data))

    def log_system(self, event: str, level: str, message: str, details: Dict[str, Any] = None):
        """Log system event"""
        log = SystemLog(
            timestamp=datetime.now().isoformat(),
            event=event,
            level=level,
            message=message,
            details=details or {}
        )
        self._write_log(LogCategory.SYSTEM, asdict(log))

    def log_error(self, error: str, details: Dict[str, Any] = None):
        """Log an error"""
        self._write_log(LogCategory.ERROR, {
            'timestamp': datetime.now().isoformat(),
            'error': error,
            'details': details or {}
        })

    # ==================== Analysis Methods ====================

    def get_daily_stats(self, date: datetime.date = None) -> Dict[str, Any]:
        """Get statistics for a specific day"""
        if date is None:
            date = datetime.now().date()

        date_str = date.strftime("%Y-%m-%d")
        trades_file = self.log_dir / LogCategory.TRADE.value / f"{date_str}.jsonl"

        trades = []
        if trades_file.exists():
            with open(trades_file, 'r') as f:
                for line in f:
                    trades.append(json.loads(line))

        if not trades:
            return {'date': date_str, 'total_trades': 0}

        # Calculate stats
        total_pnl = 0
        winning = 0
        losing = 0
        buy_trades = []
        sell_trades = []

        for trade in trades:
            if trade['action'] in ['BUY', 'COVER']:
                buy_trades.append(trade)
            else:
                sell_trades.append(trade)

        return {
            'date': date_str,
            'total_trades': len(trades),
            'buy_trades': len(buy_trades),
            'sell_trades': len(sell_trades),
            'symbols_traded': list(set(t['symbol'] for t in trades)),
            'total_volume': sum(t['quantity'] * t['price'] for t in trades),
            'strategies_used': list(set(t.get('strategy', 'unknown') for t in trades))
        }

    def get_trade_history(self, days: int = 7, symbol: str = None) -> List[Dict]:
        """Get trade history for analysis"""
        trades = []
        end_date = datetime.now().date()
        start_date = end_date - timedelta(days=days)

        current_date = start_date
        while current_date <= end_date:
            date_str = current_date.strftime("%Y-%m-%d")
            trades_file = self.log_dir / LogCategory.TRADE.value / f"{date_str}.jsonl"

            if trades_file.exists():
                with open(trades_file, 'r') as f:
                    for line in f:
                        trade = json.loads(line)
                        if symbol is None or trade['symbol'] == symbol:
                            trades.append(trade)

            current_date += timedelta(days=1)

        return trades

    def get_performance_history(self, days: int = 7) -> List[Dict]:
        """Get performance snapshots for analysis"""
        snapshots = []
        end_date = datetime.now().date()
        start_date = end_date - timedelta(days=days)

        current_date = start_date
        while current_date <= end_date:
            date_str = current_date.strftime("%Y-%m-%d")
            perf_file = self.log_dir / LogCategory.PERFORMANCE.value / f"{date_str}.jsonl"

            if perf_file.exists():
                with open(perf_file, 'r') as f:
                    for line in f:
                        snapshots.append(json.loads(line))

            current_date += timedelta(days=1)

        return snapshots

    def get_decision_analysis(self, days: int = 7, symbol: str = None) -> Dict[str, Any]:
        """Analyze trading decisions"""
        decisions = []
        end_date = datetime.now().date()
        start_date = end_date - timedelta(days=days)

        current_date = start_date
        while current_date <= end_date:
            date_str = current_date.strftime("%Y-%m-%d")
            decisions_file = self.log_dir / LogCategory.DECISION.value / f"{date_str}.jsonl"

            if decisions_file.exists():
                with open(decisions_file, 'r') as f:
                    for line in f:
                        decision = json.loads(line)
                        if symbol is None or decision['symbol'] == symbol:
                            decisions.append(decision)

            current_date += timedelta(days=1)

        if not decisions:
            return {'total_decisions': 0}

        # Analyze decisions
        decision_counts = {}
        reason_counts = {}
        confidence_by_decision = {}

        for d in decisions:
            dec = d['decision']
            decision_counts[dec] = decision_counts.get(dec, 0) + 1

            reason = d.get('reason', 'unknown')
            reason_counts[reason] = reason_counts.get(reason, 0) + 1

            if dec not in confidence_by_decision:
                confidence_by_decision[dec] = []
            confidence_by_decision[dec].append(d.get('confidence', 0))

        avg_confidence = {
            k: sum(v) / len(v) if v else 0
            for k, v in confidence_by_decision.items()
        }

        return {
            'total_decisions': len(decisions),
            'decision_breakdown': decision_counts,
            'top_reasons': dict(sorted(reason_counts.items(), key=lambda x: x[1], reverse=True)[:10]),
            'avg_confidence_by_decision': avg_confidence
        }

    def export_to_csv(self, category: LogCategory, output_file: str, days: int = 30):
        """Export logs to CSV for external analysis"""
        data = []
        end_date = datetime.now().date()
        start_date = end_date - timedelta(days=days)

        current_date = start_date
        while current_date <= end_date:
            date_str = current_date.strftime("%Y-%m-%d")
            log_file = self.log_dir / category.value / f"{date_str}.jsonl"

            if log_file.exists():
                with open(log_file, 'r') as f:
                    for line in f:
                        data.append(json.loads(line))

            current_date += timedelta(days=1)

        if not data:
            return

        # Flatten nested dicts for CSV
        flat_data = []
        for entry in data:
            flat_entry = {}
            for key, value in entry.items():
                if isinstance(value, dict):
                    for k, v in value.items():
                        flat_entry[f"{key}_{k}"] = v
                else:
                    flat_entry[key] = value
            flat_data.append(flat_entry)

        # Get all unique keys
        all_keys = set()
        for entry in flat_data:
            all_keys.update(entry.keys())

        with open(output_file, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=sorted(all_keys))
            writer.writeheader()
            writer.writerows(flat_data)

    def get_summary_report(self) -> Dict[str, Any]:
        """Generate a summary report of all analytics"""
        today = datetime.now().date()

        return {
            'generated_at': datetime.now().isoformat(),
            'today_stats': self.get_daily_stats(today),
            'week_trades': len(self.get_trade_history(days=7)),
            'week_decisions': self.get_decision_analysis(days=7),
            'recent_performance': self._performance_buffer[-10:] if self._performance_buffer else [],
            'log_files': {
                cat.value: len(list((self.log_dir / cat.value).glob("*.jsonl")))
                for cat in LogCategory
            }
        }


# Global instance
analytics_logger = AnalyticsLogger()


# Convenience functions
def log_trade(symbol: str, action: str, quantity: int, price: float,
              order_type: str = "MARKET", side: str = "long",
              reason: str = "", strategy: str = "", confidence: float = 0.0,
              stop_loss: float = 0.0, take_profit: float = 0.0,
              account_balance: float = 0.0, mode: str = "simulation",
              **kwargs):
    """Quick trade logging"""
    trade = TradeLog(
        timestamp=datetime.now().isoformat(),
        symbol=symbol,
        action=action,
        quantity=quantity,
        price=price,
        order_type=order_type,
        side=side,
        reason=reason,
        strategy=strategy,
        confidence=confidence,
        stop_loss=stop_loss,
        take_profit=take_profit,
        position_value=quantity * price,
        account_balance=account_balance,
        mode=mode,
        **kwargs
    )
    analytics_logger.log_trade(trade)


def log_decision(symbol: str, decision: str, reason: str,
                 factors: Dict = None, signals: Dict = None,
                 indicators: Dict = None, confidence: float = 0.0,
                 mode: str = "simulation"):
    """Quick decision logging"""
    dec = DecisionLog(
        timestamp=datetime.now().isoformat(),
        symbol=symbol,
        decision=decision,
        reason=reason,
        factors=factors or {},
        signals=signals or {},
        indicators=indicators or {},
        risk_assessment={},
        confidence=confidence,
        mode=mode
    )
    analytics_logger.log_decision(dec)


def log_signal(symbol: str, strategy: str, signal: str,
               strength: float, price: float, volume: float = 0,
               indicators: Dict = None, conditions_met: List = None):
    """Quick signal logging"""
    sig = SignalLog(
        timestamp=datetime.now().isoformat(),
        symbol=symbol,
        strategy=strategy,
        signal=signal,
        strength=strength,
        indicators=indicators or {},
        conditions_met=conditions_met or [],
        price=price,
        volume=volume
    )
    analytics_logger.log_signal(sig)


def log_performance(account_balance: float, daily_pnl: float,
                    total_pnl: float, win_rate: float,
                    total_trades: int, open_positions: int,
                    mode: str = "simulation", **kwargs):
    """Quick performance logging"""
    perf = PerformanceLog(
        timestamp=datetime.now().isoformat(),
        account_balance=account_balance,
        daily_pnl=daily_pnl,
        total_pnl=total_pnl,
        unrealized_pnl=kwargs.get('unrealized_pnl', 0),
        realized_pnl=kwargs.get('realized_pnl', 0),
        win_rate=win_rate,
        profit_factor=kwargs.get('profit_factor', 0),
        sharpe_ratio=kwargs.get('sharpe_ratio', 0),
        max_drawdown=kwargs.get('max_drawdown', 0),
        current_drawdown=kwargs.get('current_drawdown', 0),
        total_trades=total_trades,
        winning_trades=kwargs.get('winning_trades', 0),
        losing_trades=kwargs.get('losing_trades', 0),
        avg_win=kwargs.get('avg_win', 0),
        avg_loss=kwargs.get('avg_loss', 0),
        largest_win=kwargs.get('largest_win', 0),
        largest_loss=kwargs.get('largest_loss', 0),
        open_positions=open_positions,
        buying_power=kwargs.get('buying_power', 0),
        mode=mode
    )
    analytics_logger.log_performance(perf)


def log_system_event(event: str, message: str, level: str = "INFO", details: Dict = None):
    """Quick system event logging"""
    analytics_logger.log_system(event, level, message, details)


def log_error(error: str, details: Dict = None):
    """Quick error logging"""
    analytics_logger.log_error(error, details)
