#!/usr/bin/env python3
"""
Institutional Trading Bot - Easy Setup Wizard
==============================================
One-time setup script to configure everything you need.
Run this once, then use 'start_trading.py' to run the bot.
"""

import os
import sys
import json
import getpass
from pathlib import Path
from datetime import datetime

# Colors for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text.center(60)}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}\n")

def print_step(step, text):
    print(f"{Colors.CYAN}[Step {step}]{Colors.END} {text}")

def print_success(text):
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.WARNING}⚠ {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.FAIL}✗ {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}ℹ {text}{Colors.END}")

def get_input(prompt, default=None, secret=False):
    """Get user input with optional default and secret mode"""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    if secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)

    return value.strip() or default

def setup_environment_file():
    """Create .env file with Schwab credentials"""
    print_header("SCHWAB API CREDENTIALS")

    print_info("You need Schwab API credentials from: https://developer.schwab.com")
    print_info("1. Create an app at developer.schwab.com")
    print_info("2. Get your API Key and App Secret")
    print_info("3. Set callback URL to: https://127.0.0.1")
    print()

    # Check for existing .env
    env_file = Path(".env")
    existing_config = {}

    if env_file.exists():
        print_warning("Existing .env file found. Loading current values...")
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    existing_config[key] = value.strip('"').strip("'")

    # Get credentials
    api_key = get_input(
        "Schwab API Key",
        default=existing_config.get('SCHWAB_API_KEY', ''),
    )

    app_secret = get_input(
        "Schwab App Secret",
        default=existing_config.get('SCHWAB_APP_SECRET', ''),
        secret=True
    )

    account_number = get_input(
        "Schwab Account Number (optional, press Enter to skip)",
        default=existing_config.get('SCHWAB_ACCOUNT_NUMBER', ''),
    )

    # Trading configuration
    print()
    print_header("TRADING CONFIGURATION")

    paper_trading = get_input(
        "Start in Paper Trading mode? (recommended for testing) [yes/no]",
        default="yes"
    ).lower() in ['yes', 'y', 'true', '1']

    max_daily_loss = get_input(
        "Maximum daily loss (dollars)",
        default=existing_config.get('MAX_DAILY_LOSS', '500')
    )

    max_position_size = get_input(
        "Maximum position size (dollars)",
        default=existing_config.get('MAX_POSITION_SIZE', '5000')
    )

    # Alerting (optional)
    print()
    print_header("ALERTS (Optional)")
    print_info("Set up alerts to get notified of trades and issues")

    telegram_token = get_input(
        "Telegram Bot Token (press Enter to skip)",
        default=existing_config.get('TELEGRAM_BOT_TOKEN', '')
    )

    telegram_chat_id = get_input(
        "Telegram Chat ID (press Enter to skip)",
        default=existing_config.get('TELEGRAM_CHAT_ID', '')
    )

    # Write .env file
    env_content = f'''# Schwab API Credentials
# Generated by setup_wizard.py on {datetime.now().isoformat()}
SCHWAB_API_KEY="{api_key}"
SCHWAB_APP_SECRET="{app_secret}"
SCHWAB_ACCOUNT_NUMBER="{account_number}"

# Trading Configuration
TRADING_ENV="{'paper' if paper_trading else 'production'}"
PAPER_TRADING="{'true' if paper_trading else 'false'}"
MAX_DAILY_LOSS="{max_daily_loss}"
MAX_POSITION_SIZE="{max_position_size}"

# Risk Limits
MAX_POSITIONS="5"
MAX_DAILY_LOSS_PERCENT="0.02"
EMERGENCY_STOP_LOSS_PERCENT="0.05"

# Alerts (Optional)
TELEGRAM_BOT_TOKEN="{telegram_token}"
TELEGRAM_CHAT_ID="{telegram_chat_id}"

# System
LOG_LEVEL="INFO"
AUTO_START="false"
'''

    with open(".env", 'w') as f:
        f.write(env_content)

    # Protect the file
    os.chmod(".env", 0o600)

    print_success(".env file created successfully!")
    return api_key, app_secret


def setup_schwab_token(api_key, app_secret):
    """Authenticate with Schwab and create token file (WSL/headless compatible)"""
    print_header("SCHWAB AUTHENTICATION")

    token_path = Path("token_1.json")

    if token_path.exists():
        print_warning("Token file already exists!")
        refresh = get_input("Do you want to refresh it? [yes/no]", default="no")
        if refresh.lower() not in ['yes', 'y']:
            print_info("Keeping existing token.")
            return True

    try:
        from schwab import auth
        from schwab.auth import OAuth2Client
        import httpx
    except ImportError:
        print_error("schwab-py not installed. Installing...")
        os.system("pip install schwab-py httpx")
        print_info("Please run setup again after installation.")
        return False

    callback_url = 'https://127.0.0.1'

    # Build the authorization URL manually
    auth_url = (
        f"https://api.schwabapi.com/v1/oauth/authorize?"
        f"client_id={api_key}&"
        f"redirect_uri={callback_url}&"
        f"response_type=code"
    )

    print_info("Manual authentication for WSL/headless environments:")
    print()
    print(f"{Colors.BOLD}Step 1:{Colors.END} Copy this URL and open it in your browser:")
    print()
    print(f"  {Colors.CYAN}{auth_url}{Colors.END}")
    print()
    print(f"{Colors.BOLD}Step 2:{Colors.END} Log in to your Schwab account and authorize the app")
    print()
    print(f"{Colors.BOLD}Step 3:{Colors.END} After authorization, you'll be redirected to a URL like:")
    print(f"  https://127.0.0.1/?code=XXXXX&session=YYYYY")
    print()
    print(f"{Colors.BOLD}Step 4:{Colors.END} Copy the ENTIRE URL from your browser (it will show an error page, that's OK)")
    print()

    redirect_url = get_input("Paste the full redirect URL here")

    if not redirect_url:
        print_error("No URL provided")
        return False

    try:
        # Extract the authorization code from the URL
        from urllib.parse import urlparse, parse_qs
        parsed = urlparse(redirect_url)
        params = parse_qs(parsed.query)

        if 'code' not in params:
            print_error("Could not find authorization code in URL")
            print_info("Make sure you copied the ENTIRE URL including the ?code=... part")
            return False

        auth_code = params['code'][0]
        print_success(f"Authorization code received!")

        # Exchange code for token - do this directly without schwab-py's manual flow
        # (schwab-py's client_from_manual_flow starts its own interactive prompt)
        print_info("Exchanging code for access token...")

        import base64

        credentials = base64.b64encode(f"{api_key}:{app_secret}".encode()).decode()

        token_response = httpx.post(
            "https://api.schwabapi.com/v1/oauth/token",
            headers={
                "Authorization": f"Basic {credentials}",
                "Content-Type": "application/x-www-form-urlencoded"
            },
            data={
                "grant_type": "authorization_code",
                "code": auth_code,
                "redirect_uri": callback_url
            }
        )

        if token_response.status_code != 200:
            print_error(f"Token exchange failed: {token_response.status_code}")
            print_error(token_response.text)
            return False

        raw_token = token_response.json()

        # Save token in schwab-py compatible format
        # schwab-py expects: {"token": {actual_token_data}, "creation_timestamp": ...}
        import time
        token_data = {
            "token": raw_token,
            "creation_timestamp": int(time.time())
        }
        with open(token_path, 'w') as f:
            json.dump(token_data, f, indent=2)

        print_success("Token saved successfully!")

        # Create client for verification
        client = auth.client_from_token_file(
            str(token_path),
            api_key,
            app_secret
        )

        # Test the connection
        response = client.get_account_numbers()
        if response.status_code == 200:
            accounts = response.json()
            print_success(f"Authentication successful! Found {len(accounts)} account(s).")

            for acc in accounts:
                acc_num = acc.get('accountNumber', 'Unknown')
                masked = acc_num[:2] + '*' * (len(acc_num) - 4) + acc_num[-2:]
                print_info(f"  Account: {masked}")

            return True
        else:
            print_error(f"API test failed: {response.status_code}")
            return False

    except Exception as e:
        print_error(f"Authentication error: {e}")
        import traceback
        traceback.print_exc()
        return False


def create_quick_start_scripts():
    """Create easy-to-use start/stop scripts"""
    print_header("CREATING CONTROL SCRIPTS")

    # Main start script
    start_script = '''#!/usr/bin/env python3
"""
Start Trading Bot
=================
Easy launcher for the institutional trading bot.
Usage: python start_trading.py [--paper] [--live] [--monitor-only]
"""

import os
import sys
import signal
import asyncio
import argparse
from pathlib import Path
from datetime import datetime

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

def print_banner():
    banner = """
    ╔══════════════════════════════════════════════════════════════╗
    ║         INSTITUTIONAL TRADING BOT v2.0                       ║
    ║         ────────────────────────────────────                 ║
    ║         Press Ctrl+C to stop safely                          ║
    ╚══════════════════════════════════════════════════════════════╝
    """
    print(banner)

def check_prerequisites():
    """Check all required files and credentials"""
    errors = []

    # Check .env file
    if not Path(".env").exists():
        errors.append("Missing .env file - run setup_wizard.py first")

    # Check token file
    if not Path("token_1.json").exists():
        errors.append("Missing token_1.json - run setup_wizard.py first")

    # Check API credentials
    if not os.getenv("SCHWAB_API_KEY"):
        errors.append("SCHWAB_API_KEY not set")
    if not os.getenv("SCHWAB_APP_SECRET"):
        errors.append("SCHWAB_APP_SECRET not set")

    return errors

def main():
    parser = argparse.ArgumentParser(description='Start the Trading Bot')
    parser.add_argument('--paper', action='store_true', help='Run in paper trading mode (default)')
    parser.add_argument('--live', action='store_true', help='Run in live trading mode')
    parser.add_argument('--monitor-only', action='store_true', help='Monitor only, no trading')
    parser.add_argument('--port', type=int, default=8000, help='Web interface port')
    args = parser.parse_args()

    print_banner()

    # Check prerequisites
    errors = check_prerequisites()
    if errors:
        print("\\n❌ Setup incomplete:")
        for error in errors:
            print(f"   • {error}")
        print("\\nRun: python setup_wizard.py")
        sys.exit(1)

    # Determine trading mode
    if args.live:
        os.environ['PAPER_TRADING'] = 'false'
        os.environ['TRADING_ENV'] = 'production'
        mode = "🔴 LIVE TRADING"
        print(f"\\n⚠️  WARNING: Running in LIVE mode - real money at risk!")
        confirm = input("Type 'LIVE' to confirm: ")
        if confirm != 'LIVE':
            print("Aborted.")
            sys.exit(0)
    else:
        os.environ['PAPER_TRADING'] = 'true'
        os.environ['TRADING_ENV'] = 'paper'
        mode = "📝 PAPER TRADING"

    if args.monitor_only:
        os.environ['MONITOR_ONLY'] = 'true'
        mode += " (Monitor Only)"

    print(f"\\n🚀 Starting in {mode} mode...")
    print(f"📊 Dashboard: http://localhost:{args.port}")
    print(f"⏰ Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("\\n" + "─" * 60)

    # Import and run the trading bot
    try:
        from trading_bot_commentary_updated import app
        import uvicorn

        uvicorn.run(app, host="0.0.0.0", port=args.port, log_level="info")

    except KeyboardInterrupt:
        print("\\n\\n🛑 Shutting down gracefully...")
        print("   Saving state and closing positions if needed...")
    except Exception as e:
        print(f"\\n❌ Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
'''

    with open("start_trading.py", 'w') as f:
        f.write(start_script)
    os.chmod("start_trading.py", 0o755)
    print_success("Created start_trading.py")

    # Stop script
    stop_script = '''#!/usr/bin/env python3
"""
Stop Trading Bot
================
Safely stop the trading bot.
"""

import os
import sys
import signal
import requests

def main():
    print("🛑 Stopping Trading Bot...")

    # Try graceful shutdown via API
    try:
        response = requests.post("http://localhost:8000/api/shutdown", timeout=5)
        if response.status_code == 200:
            print("✓ Graceful shutdown initiated")
            return
    except:
        pass

    # Find and kill process
    import subprocess
    result = subprocess.run(
        ["pgrep", "-f", "trading_bot_commentary_updated"],
        capture_output=True, text=True
    )

    if result.stdout.strip():
        pids = result.stdout.strip().split("\\n")
        for pid in pids:
            try:
                os.kill(int(pid), signal.SIGTERM)
                print(f"✓ Sent SIGTERM to process {pid}")
            except:
                pass
    else:
        print("No trading bot process found")

if __name__ == "__main__":
    main()
'''

    with open("stop_trading.py", 'w') as f:
        f.write(stop_script)
    os.chmod("stop_trading.py", 0o755)
    print_success("Created stop_trading.py")

    # Status script
    status_script = '''#!/usr/bin/env python3
"""
Trading Bot Status
==================
Check the current status of the trading bot.
"""

import os
import sys
import json
import requests
from datetime import datetime

def get_status():
    """Get bot status from API"""
    try:
        response = requests.get("http://localhost:8000/api/status", timeout=5)
        if response.status_code == 200:
            return response.json()
    except:
        return None

def get_positions():
    """Get current positions"""
    try:
        response = requests.get("http://localhost:8000/api/positions", timeout=5)
        if response.status_code == 200:
            return response.json()
    except:
        return None

def get_pnl():
    """Get P&L"""
    try:
        response = requests.get("http://localhost:8000/api/pnl", timeout=5)
        if response.status_code == 200:
            return response.json()
    except:
        return None

def main():
    print("\\n" + "═" * 60)
    print("       TRADING BOT STATUS")
    print("═" * 60)

    status = get_status()

    if not status:
        print("\\n❌ Bot is NOT running or not responding")
        print("   Start with: python start_trading.py")
        return

    print(f"\\n✅ Bot is RUNNING")
    print(f"   Mode: {status.get('mode', 'Unknown')}")
    print(f"   State: {status.get('state', 'Unknown')}")
    print(f"   Uptime: {status.get('uptime', 'Unknown')}")

    # Positions
    positions = get_positions()
    if positions:
        print(f"\\n📊 POSITIONS ({len(positions)} open)")
        print("   " + "-" * 50)
        for pos in positions:
            symbol = pos.get('symbol', '?')
            qty = pos.get('quantity', 0)
            pnl = pos.get('unrealized_pnl', 0)
            pnl_color = '🟢' if pnl >= 0 else '🔴'
            print(f"   {symbol}: {qty} shares | P&L: {pnl_color} ${pnl:,.2f}")

    # P&L
    pnl_data = get_pnl()
    if pnl_data:
        daily = pnl_data.get('daily_pnl', 0)
        total = pnl_data.get('total_pnl', 0)
        print(f"\\n💰 P&L")
        print("   " + "-" * 50)
        print(f"   Today: {'🟢' if daily >= 0 else '🔴'} ${daily:,.2f}")
        print(f"   Total: {'🟢' if total >= 0 else '🔴'} ${total:,.2f}")

    print("\\n" + "═" * 60)
    print(f"   Dashboard: http://localhost:8000")
    print(f"   Checked at: {datetime.now().strftime('%H:%M:%S')}")
    print("═" * 60 + "\\n")

if __name__ == "__main__":
    main()
'''

    with open("status_trading.py", 'w') as f:
        f.write(status_script)
    os.chmod("status_trading.py", 0o755)
    print_success("Created status_trading.py")

    # Emergency stop script
    emergency_script = '''#!/usr/bin/env python3
"""
EMERGENCY STOP
==============
Immediately close all positions and stop trading.
USE ONLY IN EMERGENCIES!
"""

import os
import sys
import requests

def main():
    print("\\n" + "!" * 60)
    print("       🚨 EMERGENCY STOP 🚨")
    print("!" * 60)
    print("\\nThis will:")
    print("  1. Close ALL open positions at market price")
    print("  2. Cancel ALL pending orders")
    print("  3. Stop the trading bot")
    print()

    confirm = input("Type 'EMERGENCY' to confirm: ")
    if confirm != 'EMERGENCY':
        print("Aborted.")
        return

    print("\\n⚠️  Executing emergency stop...")

    try:
        # Close all positions
        response = requests.post(
            "http://localhost:8000/api/emergency/close-all",
            timeout=30
        )
        if response.status_code == 200:
            print("✓ All positions closed")
        else:
            print(f"⚠ Position close response: {response.status_code}")

        # Shutdown bot
        response = requests.post(
            "http://localhost:8000/api/shutdown",
            timeout=10
        )
        print("✓ Bot shutdown initiated")

    except Exception as e:
        print(f"\\n⚠️  API not responding. Attempting force stop...")

        # Force kill
        import subprocess
        subprocess.run(["pkill", "-f", "trading_bot"], capture_output=True)
        print("✓ Processes terminated")

    print("\\n✅ Emergency stop complete")
    print("   Check your Schwab account directly to verify positions")

if __name__ == "__main__":
    main()
'''

    with open("emergency_stop.py", 'w') as f:
        f.write(emergency_script)
    os.chmod("emergency_stop.py", 0o755)
    print_success("Created emergency_stop.py")


def create_config_file():
    """Create Config().yaml with sensible defaults"""
    print_header("CREATING CONFIGURATION")

    config_content = '''# Trading Bot Configuration
# Generated by setup_wizard.py

# Schwab API Configuration
schwab:
  callback_url: "https://127.0.0.1"
  token_path: "token_1.json"

# Trading Parameters
trading:
  max_positions: 5
  max_position_value: 5000
  max_portfolio_percent: 0.15
  min_position_value: 100

  # Risk Limits
  max_daily_loss_percent: 0.02
  max_daily_loss_absolute: 500
  max_drawdown_percent: 0.10

  # Stop Loss / Take Profit
  default_stop_loss_percent: 0.02
  default_take_profit_percent: 0.04
  use_trailing_stops: true
  trailing_stop_percent: 0.015

  # Extended Hours
  extended_hours:
    allow_premarket: false
    allow_afterhours: false
    use_limit_orders: true

# ML Model Settings
ml:
  enabled: true
  confidence_threshold: 0.60
  retrain_days: 7

# Strategies
strategies:
  enabled:
    - breakout
    - mean_reversion
    - momentum
  min_consensus: 2

# Commentary System
commentary:
  enabled: true
  detail_level: "normal"  # minimal, normal, verbose
  max_history: 100

# Logging
logging:
  level: "INFO"
  file: "trading_bot.log"
  max_size_mb: 50
  backup_count: 5

# Backtesting
backtesting:
  enabled: true
  initial_capital: 100000
  commission: 0.005
  slippage: 0.001

# Technical Analysis (required)
technical_analysis:
  timeframes:
    - 1min
    - 5min
    - 15min
    - 1hour
    - 1day
  fibonacci_levels:
    - 0.236
    - 0.382
    - 0.5
    - 0.618
    - 0.786

# Order Management
order_management:
  auto_cancel_existing_orders: true
  require_close_confirmation: true
  confirm_only_losses: false
  confirm_threshold_percent: 5

# Error Recovery
error_recovery:
  max_retries: 3
  retry_delay: 1.0
  circuit_breaker_enabled: true
  max_daily_loss_threshold: 0.10
  emergency_stop_loss: 0.15

# Performance Metrics
performance_metrics:
  calculate_sharpe: true
  calculate_sortino: true
  calculate_max_drawdown: true
  risk_free_rate: 0.02

# Paths
paths:
  trade_journal: "trade_journal.json"
  model: "trading_model.pkl"
  log: "trading_bot.log"
  commentary_log: "trading_commentary.json"
  backtest_results: "backtest_results.json"
'''

    with open("Config().yaml", 'w') as f:
        f.write(config_content)

    print_success("Created Config().yaml")


def install_dependencies():
    """Install required Python packages"""
    print_header("INSTALLING DEPENDENCIES")

    packages = [
        "schwab-py",
        "python-dotenv",
        "requests",
        "fastapi",
        "uvicorn",
        "websockets",
        "numpy",
        "pandas",
        "scikit-learn",
        "ta",
        "textblob",
        "pyyaml",
        "rich",
    ]

    print_info("Installing required packages...")

    import subprocess
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "--quiet"] + packages,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print_success("All dependencies installed!")
    else:
        print_warning("Some packages may have failed to install")
        print_info("You can install manually: pip install " + " ".join(packages))


def print_final_instructions():
    """Print final setup instructions"""
    print_header("SETUP COMPLETE!")

    print(f"""
{Colors.GREEN}Your trading bot is ready!{Colors.END}

{Colors.BOLD}Quick Start Commands:{Colors.END}

  {Colors.CYAN}python start_trading.py{Colors.END}        # Start in paper trading mode
  {Colors.CYAN}python start_trading.py --live{Colors.END} # Start in LIVE mode (real money)
  {Colors.CYAN}python status_trading.py{Colors.END}       # Check bot status
  {Colors.CYAN}python stop_trading.py{Colors.END}         # Stop the bot gracefully
  {Colors.CYAN}python emergency_stop.py{Colors.END}       # Emergency stop (closes all positions)

{Colors.BOLD}Web Dashboard:{Colors.END}

  http://localhost:8000              # Main dashboard
  http://localhost:8000/api/status   # API status
  http://localhost:8000/api/positions # Current positions

{Colors.BOLD}Important Files:{Colors.END}

  .env                    # Your API credentials (keep secret!)
  token_1.json           # Schwab auth token (keep secret!)
  Config().yaml          # Trading configuration
  trading_state*.json    # Bot state (positions, history)

{Colors.WARNING}Safety Reminders:{Colors.END}

  • Start with PAPER TRADING to test
  • Set conservative daily loss limits
  • Monitor the bot regularly
  • Keep emergency_stop.py handy
  • Never share your .env or token files

{Colors.BOLD}Need Help?{Colors.END}

  • Check OPERATIONS_RUNBOOK.md for procedures
  • Check trading_bot.log for errors
  • Dashboard shows real-time status

Happy Trading! 🚀
""")


def main():
    """Main setup wizard"""
    print_header("INSTITUTIONAL TRADING BOT SETUP")

    print("""
Welcome to the Trading Bot Setup Wizard!

This will help you configure:
  1. Schwab API credentials
  2. Authentication with Schwab
  3. Trading parameters
  4. Control scripts
    """)

    proceed = get_input("Ready to begin? [yes/no]", default="yes")
    if proceed.lower() not in ['yes', 'y']:
        print("Setup cancelled.")
        return

    # Step 1: Install dependencies
    print_step(1, "Installing dependencies...")
    install_dependencies()

    # Step 2: Environment file
    print_step(2, "Configuring credentials...")
    api_key, app_secret = setup_environment_file()

    # Step 3: Schwab authentication
    print_step(3, "Authenticating with Schwab...")
    if api_key and app_secret:
        setup_schwab_token(api_key, app_secret)
    else:
        print_warning("Skipping authentication - no credentials provided")

    # Step 4: Create config
    print_step(4, "Creating configuration...")
    create_config_file()

    # Step 5: Create control scripts
    print_step(5, "Creating control scripts...")
    create_quick_start_scripts()

    # Done!
    print_final_instructions()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
